### ISSUE TITLE
数据视图表关联字段选择时报错无法选中

### ISSUE THREAD

**Issue by 6iFancy** [yqwoe/datart-vite#3]
![PixPin_2024-03-26_18-10-39](https://github.com/yqwoe/datart-vite/assets/30684950/41fdc266-55a7-44dc-8e28-7834e4f68a93)
![PixPin_2024-03-26_18-10-50](https://github.com/yqwoe/datart-vite/assets/30684950/d291c17a-5597-412a-9512-dc3b06b31ffa)

**Comment by yqwoe** [comment]
> ![PixPin_2024-03-26_18-10-39](https://github.com/yqwoe/datart-vite/assets/30684950/41fdc266-55a7-44dc-8e28-7834e4f68a93)
> 
> ![PixPin_2024-03-26_18-10-50](https://github.com/yqwoe/datart-vite/assets/30684950/d291c17a-5597-412a-9512-dc3b06b31ffa)
> 
> 

好的，我看下问题
